import { LibreDwg } from "@mlightcad/libredwg-web";
const bytes = await Bun.file("/tmp/cad/s.dwg").arrayBuffer();
const lib = await LibreDwg.create("/dev-server/node_modules/@mlightcad/libredwg-web/wasm");
const db = lib.convert(lib.dwg_read_data(bytes, 0)!);
const ents = db.entities as any[];
const lw = ents.find(e=>e.type==="LWPOLYLINE");
console.log("lw vertices sample", JSON.stringify(lw.vertices?.slice(0,2)));
const pl = ents.find(e=>e.type==="POLYLINE3D");
console.log("pl3d", JSON.stringify(pl?.vertices?.slice(0,2)));
const t = ents.find(e=>e.type==="TEXT"); console.log("text", JSON.stringify({t:t.text,sp:t.startPoint}));
const mt = ents.find(e=>e.type==="MTEXT"); console.log("mtext", JSON.stringify({t:mt.text,ip:mt.insertionPoint}));
