/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCreditosRouteImport } from './routes/_authenticated/creditos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedAnalisesIdRouteImport } from './routes/_authenticated/analises.$id'
import { Route as AuthenticatedComparacoesIdRouteImport } from './routes/_authenticated/comparacoes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreditosRoute = AuthenticatedCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalisesIdRoute = AuthenticatedAnalisesIdRouteImport.update({
  id: '/analises/$id',
  path: '/analises/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComparacoesIdRoute =
  AuthenticatedComparacoesIdRouteImport.update({
    id: '/comparacoes/$id',
    path: '/comparacoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/analises/$id': typeof AuthenticatedAnalisesIdRoute
  '/comparacoes/$id': typeof AuthenticatedComparacoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/analises/$id': typeof AuthenticatedAnalisesIdRoute
  '/comparacoes/$id': typeof AuthenticatedComparacoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/creditos': typeof AuthenticatedCreditosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/analises/$id': typeof AuthenticatedAnalisesIdRoute
  '/_authenticated/comparacoes/$id': typeof AuthenticatedComparacoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/creditos'
    | '/painel'
    | '/analises/$id'
    | '/comparacoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/creditos'
    | '/painel'
    | '/analises/$id'
    | '/comparacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/creditos'
    | '/_authenticated/painel'
    | '/_authenticated/analises/$id'
    | '/_authenticated/comparacoes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/creditos': {
      id: '/_authenticated/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AuthenticatedCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analises/$id': {
      id: '/_authenticated/analises/$id'
      path: '/analises/$id'
      fullPath: '/analises/$id'
      preLoaderRoute: typeof AuthenticatedAnalisesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparacoes/$id': {
      id: '/_authenticated/comparacoes/$id'
      path: '/comparacoes/$id'
      fullPath: '/comparacoes/$id'
      preLoaderRoute: typeof AuthenticatedComparacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCreditosRoute: typeof AuthenticatedCreditosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedAnalisesIdRoute: typeof AuthenticatedAnalisesIdRoute
  AuthenticatedComparacoesIdRoute: typeof AuthenticatedComparacoesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCreditosRoute: AuthenticatedCreditosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedAnalisesIdRoute: AuthenticatedAnalisesIdRoute,
  AuthenticatedComparacoesIdRoute: AuthenticatedComparacoesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
