/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckindexRouteImport } from './routes/checkindex'
import { Route as ChecktituloRouteImport } from './routes/checktitulo'
import { Route as GeoconfrontoRouteImport } from './routes/geoconfronto'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedCreditosRouteImport } from './routes/_authenticated/creditos'
import { Route as AuthenticatedNormasRouteImport } from './routes/_authenticated/normas'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAnalisesIdRouteImport } from './routes/_authenticated/analises.$id'
import { Route as AuthenticatedComparacoesIdRouteImport } from './routes/_authenticated/comparacoes.$id'
import { Route as AuthenticatedIndexacaoIndexRouteImport } from './routes/_authenticated/indexacao.index'
import { Route as AuthenticatedIndexacaoIdRouteImport } from './routes/_authenticated/indexacao.$id'
import { Route as AuthenticatedQualificacaoIndexRouteImport } from './routes/_authenticated/qualificacao.index'
import { Route as AuthenticatedQualificacaoIdRouteImport } from './routes/_authenticated/qualificacao.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckindexRoute = CheckindexRouteImport.update({
  id: '/checkindex',
  path: '/checkindex',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecktituloRoute = ChecktituloRouteImport.update({
  id: '/checktitulo',
  path: '/checktitulo',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoconfrontoRoute = GeoconfrontoRouteImport.update({
  id: '/geoconfronto',
  path: '/geoconfronto',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditosRoute = AuthenticatedCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNormasRoute = AuthenticatedNormasRouteImport.update({
  id: '/normas',
  path: '/normas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAnalisesIdRoute = AuthenticatedAnalisesIdRouteImport.update({
  id: '/analises/$id',
  path: '/analises/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComparacoesIdRoute =
  AuthenticatedComparacoesIdRouteImport.update({
    id: '/comparacoes/$id',
    path: '/comparacoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndexacaoIndexRoute =
  AuthenticatedIndexacaoIndexRouteImport.update({
    id: '/indexacao/',
    path: '/indexacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIndexacaoIdRoute =
  AuthenticatedIndexacaoIdRouteImport.update({
    id: '/indexacao/$id',
    path: '/indexacao/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQualificacaoIndexRoute =
  AuthenticatedQualificacaoIndexRouteImport.update({
    id: '/qualificacao/',
    path: '/qualificacao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQualificacaoIdRoute =
  AuthenticatedQualificacaoIdRouteImport.update({
    id: '/qualificacao/$id',
    path: '/qualificacao/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkindex': typeof CheckindexRoute
  '/checktitulo': typeof ChecktituloRoute
  '/geoconfronto': typeof GeoconfrontoRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conta': typeof AuthenticatedContaRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/normas': typeof AuthenticatedNormasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/analises/$id': typeof AuthenticatedAnalisesIdRoute
  '/comparacoes/$id': typeof AuthenticatedComparacoesIdRoute
  '/indexacao/$id': typeof AuthenticatedIndexacaoIdRoute
  '/qualificacao/$id': typeof AuthenticatedQualificacaoIdRoute
  '/indexacao/': typeof AuthenticatedIndexacaoIndexRoute
  '/qualificacao/': typeof AuthenticatedQualificacaoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkindex': typeof CheckindexRoute
  '/checktitulo': typeof ChecktituloRoute
  '/geoconfronto': typeof GeoconfrontoRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/conta': typeof AuthenticatedContaRoute
  '/creditos': typeof AuthenticatedCreditosRoute
  '/normas': typeof AuthenticatedNormasRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/analises/$id': typeof AuthenticatedAnalisesIdRoute
  '/comparacoes/$id': typeof AuthenticatedComparacoesIdRoute
  '/indexacao/$id': typeof AuthenticatedIndexacaoIdRoute
  '/qualificacao/$id': typeof AuthenticatedQualificacaoIdRoute
  '/indexacao': typeof AuthenticatedIndexacaoIndexRoute
  '/qualificacao': typeof AuthenticatedQualificacaoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkindex': typeof CheckindexRoute
  '/checktitulo': typeof ChecktituloRoute
  '/geoconfronto': typeof GeoconfrontoRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/creditos': typeof AuthenticatedCreditosRoute
  '/_authenticated/normas': typeof AuthenticatedNormasRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/analises/$id': typeof AuthenticatedAnalisesIdRoute
  '/_authenticated/comparacoes/$id': typeof AuthenticatedComparacoesIdRoute
  '/_authenticated/indexacao/$id': typeof AuthenticatedIndexacaoIdRoute
  '/_authenticated/qualificacao/$id': typeof AuthenticatedQualificacaoIdRoute
  '/_authenticated/indexacao/': typeof AuthenticatedIndexacaoIndexRoute
  '/_authenticated/qualificacao/': typeof AuthenticatedQualificacaoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkindex'
    | '/checktitulo'
    | '/geoconfronto'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/conta'
    | '/creditos'
    | '/normas'
    | '/painel'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/analises/$id'
    | '/comparacoes/$id'
    | '/indexacao/$id'
    | '/qualificacao/$id'
    | '/indexacao/'
    | '/qualificacao/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkindex'
    | '/checktitulo'
    | '/geoconfronto'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/conta'
    | '/creditos'
    | '/normas'
    | '/painel'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/analises/$id'
    | '/comparacoes/$id'
    | '/indexacao/$id'
    | '/qualificacao/$id'
    | '/indexacao'
    | '/qualificacao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkindex'
    | '/checktitulo'
    | '/geoconfronto'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/conta'
    | '/_authenticated/creditos'
    | '/_authenticated/normas'
    | '/_authenticated/painel'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/analises/$id'
    | '/_authenticated/comparacoes/$id'
    | '/_authenticated/indexacao/$id'
    | '/_authenticated/qualificacao/$id'
    | '/_authenticated/indexacao/'
    | '/_authenticated/qualificacao/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckindexRoute: typeof CheckindexRoute
  ChecktituloRoute: typeof ChecktituloRoute
  GeoconfrontoRoute: typeof GeoconfrontoRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkindex': {
      id: '/checkindex'
      path: '/checkindex'
      fullPath: '/checkindex'
      preLoaderRoute: typeof CheckindexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checktitulo': {
      id: '/checktitulo'
      path: '/checktitulo'
      fullPath: '/checktitulo'
      preLoaderRoute: typeof ChecktituloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geoconfronto': {
      id: '/geoconfronto'
      path: '/geoconfronto'
      fullPath: '/geoconfronto'
      preLoaderRoute: typeof GeoconfrontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/creditos': {
      id: '/_authenticated/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof AuthenticatedCreditosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/normas': {
      id: '/_authenticated/normas'
      path: '/normas'
      fullPath: '/normas'
      preLoaderRoute: typeof AuthenticatedNormasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analises/$id': {
      id: '/_authenticated/analises/$id'
      path: '/analises/$id'
      fullPath: '/analises/$id'
      preLoaderRoute: typeof AuthenticatedAnalisesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparacoes/$id': {
      id: '/_authenticated/comparacoes/$id'
      path: '/comparacoes/$id'
      fullPath: '/comparacoes/$id'
      preLoaderRoute: typeof AuthenticatedComparacoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indexacao/': {
      id: '/_authenticated/indexacao/'
      path: '/indexacao'
      fullPath: '/indexacao/'
      preLoaderRoute: typeof AuthenticatedIndexacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indexacao/$id': {
      id: '/_authenticated/indexacao/$id'
      path: '/indexacao/$id'
      fullPath: '/indexacao/$id'
      preLoaderRoute: typeof AuthenticatedIndexacaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qualificacao/': {
      id: '/_authenticated/qualificacao/'
      path: '/qualificacao'
      fullPath: '/qualificacao/'
      preLoaderRoute: typeof AuthenticatedQualificacaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qualificacao/$id': {
      id: '/_authenticated/qualificacao/$id'
      path: '/qualificacao/$id'
      fullPath: '/qualificacao/$id'
      preLoaderRoute: typeof AuthenticatedQualificacaoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedCreditosRoute: typeof AuthenticatedCreditosRoute
  AuthenticatedNormasRoute: typeof AuthenticatedNormasRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedAnalisesIdRoute: typeof AuthenticatedAnalisesIdRoute
  AuthenticatedComparacoesIdRoute: typeof AuthenticatedComparacoesIdRoute
  AuthenticatedIndexacaoIdRoute: typeof AuthenticatedIndexacaoIdRoute
  AuthenticatedQualificacaoIdRoute: typeof AuthenticatedQualificacaoIdRoute
  AuthenticatedIndexacaoIndexRoute: typeof AuthenticatedIndexacaoIndexRoute
  AuthenticatedQualificacaoIndexRoute: typeof AuthenticatedQualificacaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedCreditosRoute: AuthenticatedCreditosRoute,
  AuthenticatedNormasRoute: AuthenticatedNormasRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedAnalisesIdRoute: AuthenticatedAnalisesIdRoute,
  AuthenticatedComparacoesIdRoute: AuthenticatedComparacoesIdRoute,
  AuthenticatedIndexacaoIdRoute: AuthenticatedIndexacaoIdRoute,
  AuthenticatedQualificacaoIdRoute: AuthenticatedQualificacaoIdRoute,
  AuthenticatedIndexacaoIndexRoute: AuthenticatedIndexacaoIndexRoute,
  AuthenticatedQualificacaoIndexRoute: AuthenticatedQualificacaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckindexRoute: CheckindexRoute,
  ChecktituloRoute: ChecktituloRoute,
  GeoconfrontoRoute: GeoconfrontoRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
